# Generated by Django 4.2.30 on 2026-09-26 06:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('video_source_type', models.CharField(choices=[('YOUTUBE', 'YouTube Video'), ('CLOUD', 'Cloudflare R2 Hosted')], default='YOUTUBE', max_length=20)),
                ('youtube_video_id', models.CharField(blank=True, max_length=100, null=True)),
                ('r2_object_key', models.CharField(blank=True, max_length=500, null=True)),
                ('thumbnail_key', models.CharField(blank=True, max_length=500, null=True)),
                ('is_free_preview', models.BooleanField(default=False)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='academics.topic')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
