# Generated by Django 4.2.30 on 2026-09-26 16:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_academicclass_course_chapter_description_lecture_and_more'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DPP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dpp_number', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.IntegerField(default=20)),
                ('is_published', models.BooleanField(default=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dpps', to='academics.chapter')),
            ],
            options={
                'ordering': ['dpp_number', 'title'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='academics.chapter'),
        ),
        migrations.CreateModel(
            name='DPPQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=1)),
                ('positive_marks', models.IntegerField(default=4)),
                ('negative_marks', models.IntegerField(default=1)),
                ('dpp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dpp_questions', to='questions.dpp')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dpp_entries', to='questions.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
